# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "2,3,4,5"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/nofilt_noglobal"
csv_root: "./datasets/splits"
checkpoints: "./checkpoints"

# Model Options
backbone: "groupvit"
aggregator: "squeeze"
embed_dim: 128

# Dataset Options
dataset: "ABIDEI"
task: "DX"
atlas: "cc400"
KFold: 10
fold: 0
n_views: 16

# Training Options
seed: 42
batch_size: 26
epochs: 400

# Optimization options
lr: 0.05
dropout: 0.3
weight_decay: 0.01
warmup_epochs: 20
scheduler: True
lambda_con: 0.5
sup_alpha: 0.3
