# distributed training
nodes: 1
gpus: 3
nr: 0
workers: 8
visible_gpus: "5,6,7"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/nofilt_noglobal"
csv_path: "/home/r20user17/mia/datasets/splits/ABIDEI_frames.csv"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "ABIDEI"
task: "DX"
KFold: 5
fold: 0
eval_steps: 5

# Training Options
seed: 42
batch_size: 16
image_size: 96
patch_size: 8
epochs: 100

# Model options
patch_size: 16

# Optimization options
lr: 2.0e-4
weight_decay: 0.01
scheduler: True
warmup_epochs: 10
