# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "2,3,5,6"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/nofilt_noglobal"
csv_root: "./datasets/splits"
checkpoints: "./checkpoints"

# Model Options
model: "graphseq"
embed_dim: 256
n_layers: 3

# Dataset Options
dataset: "ABIDEI"
task: "DX"
atlas: "cc400"
cnp: "AGE_AT_SCAN, BMI"
cp: "SITE_ID, SEX, HANDEDNESS_CATEGORY, CURRENT_MED_STATUS, EYE_STATUS_AT_SCAN"
KFold: 10
fold: 0
n_views: 6

# Training Options
seed: 42
batch_size: 20
epochs: 500

# Optimization options
lr: 0.05
dropout: 0.5
weight_decay: 0.05
warmup_epochs: 10
scheduler: True
lambda_con: 0.0
sup_alpha: 0.3
