# distributed training
nodes: 1
gpus: 3
nr: 0
workers: 0
visible_gpus: "5,6,7"

# Paths
data_root: "/home/r20user17/Documents/ABIDEI_frames"
csv_path: "/home/r20user17/mia/datasets/splits/ABIDEI_frames.csv"
checkpoints: "./checkpoints"

# Model Options
backbone: "swin"

# Dataset Options
dataset: "ABIDEI"
task: "DX"
KFold: 5
fold: 0
eval_steps: 1

# Training Options
seed: 42
batch_size: 32
image_size: 96
patch_size: 8
epochs: 100

# Optimization options
lr: 2.0e-3
weight_decay: 0.01
scheduler: True
warmup_epochs: 10
