# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "0,1,2,3"

# Paths
data_root: "/home/r20user17/Documents/ABIDEI_frames"
frame_csv_path: "/home/r20user17/mia/datasets/splits/ABIDEI_frames.csv"
fmri_csv_path: "/home/r20user17/mia/datasets/splits/ABIDEI_fMRI.csv"
checkpoints: "./checkpoints"

# Model Options
backbone: "groupvit"
embed_dim: 1024

# Dataset Options
dataset: "ABIDEI"
task: "DX"
KFold: 5
fold: 0

# Training Options
seed: 42
batch_size: 4
image_size: 96
patch_size: 8
epochs: 100

# Optimization options
lr_e: 2.0e-3
lr_m: 2.0e-4
weight_decay: 0.01

