# distributed training
nodes: 1
gpus: 2
nr: 0
workers: 0
visible_gpus: "4,5"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/nofilt_noglobal"
csv_path: "./datasets/splits/ABIDEI_ROI.csv"
checkpoints: "./checkpoints"

# Model Options
backbone: "groupvit"
aggregator: "avgpool"
time_length: 128
region_expand: 1
time_expand: 1

# Dataset Options
dataset: "ABIDEI"
task: "DX"
atlas: "cc400"
KFold: 10
fold: 0

# Training Options
seed: 42
batch_size: 32
num_roi: 392 # for cc 400 atlas
epochs: 200

# Optimization options
lr: 0.01
dropout: 0.3
weight_decay: 0.01
warmup_epochs: 20
scheduler: True
lambda_attn: 0.0
