# distributed training
nodes: 1
gpus: 1
nr: 0
workers: 0
visible_gpus: "0"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/filt_noglobal"
csv_root: "./datasets/splits"
checkpoints: "./checkpoints"

# Model Options
model: "graphseq"
embed_dim: 256
d_inner: 512
n_layers: 5
d_x: 32
brain_graph: ""

# Dataset Options
dataset: "ABIDEI"
task: "DX"
atlas: "cc400"
cnp: "AGE_AT_SCAN, BMI"
cp: "SEX, HANDEDNESS_CATEGORY, CURRENT_MED_STATUS"
KFold: 5
fold: 1
n_views: 14

# Training Options
seed: 42
batch_size: 20
epochs: 200

# Optimization options
optimizer: "Adam"
pcgrad: False
lr: 1.0e-4
beta1: 0.9
beta2: 0.999
lr_ttt: 1.0e-4
dropout: 0.4
weight_decay: 0.01
warmup_epochs: 10
scheduler: True
lambda_con: 0.05
temp_con: 0.07

