# distributed training
nodes: 1
gpus: 2
nr: 0
workers: 0
visible_gpus: "4,6"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/nofilt_noglobal"
csv_root: "./datasets/splits"
checkpoints: "./checkpoints"

# Model Options
backbone: "groupvit"
aggregator: "squeeze"
embed_dim: 128

# Dataset Options
dataset: "ABIDEI"
task: "DX"
atlas: "cc400"
KFold: 10
fold: 0
n_views: 8

# Training Options
seed: 42
batch_size: 24
epochs: 200

# Optimization options
lr: 0.01
dropout: 0.3
weight_decay: 0.01
warmup_epochs: 20
scheduler: True
lambda_con: 0.1
sup_alpha: 0.3
