# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "3,4,5,6"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/nofilt_noglobal"
csv_root: "./datasets/splits"
checkpoints: "./checkpoints"

# Model Options
model: "graphseq"
embed_dim: 256
n_layers: 1
window_size: 5
cls_token: True
pooler: False

# Dataset Options
dataset: "ABIDEI"
task: "DX"
atlas: "cc400"
cnp: "AGE_AT_SCAN, BMI"
cp: "SITE_ID, SEX, HANDEDNESS_CATEGORY, CURRENT_MED_STATUS, EYE_STATUS_AT_SCAN"
KFold: 5
fold: 1
n_views: 12

# Training Options
seed: 42
batch_size: 26
epochs: 400

# Optimization options
optimizer: "Adam"
lr: 0.001
lr_ttt: 1.0e-4
dropout: 0.3
weight_decay: 0.01
warmup_epochs: 10
scheduler: True
lambda_cp: 0.05
lambda_cnp: 5
sup_alpha: 0.3
ema_decay: 0.999
l_lambda: 10
f_lambda: 5
