# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "0,1,2,3"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/filt_noglobal"
train_csv: "./datasets/splits/ABIDE_Training.csv"
test_csv: "./datasets/splits/ABIDE_Testing.csv"
val_csv: "./datasets/splits/ABIDE_Validation.csv"
checkpoints: "./checkpoints"
reload: "./checkpoints/ABIDE_BNT_cc400_DX_AUC_0.7891_.pth"

# Model Options
model: "graphseq"
embed_dim: 256
d_inner: 1024
n_layers: 5
d_x: 32
spatial_attention: True
temporal_attention: True

# Dataset Options
dataset: "ABIDE_BNT"
task: "DX"
atlas: "cc400"
cnp: "AGE_AT_SCAN, HANDEDNESS_SCORES"
cp: "SEX, HANDEDNESS_CATEGORY, EYE_STATUS_AT_SCAN"
n_views: 12

# Training Options
seed: 42
batch_size: 32
epochs: 200
mixup: True

# Optimization options
optimizer: "Adam"
pcgrad: False
lr: 1.5e-4
ttpl_lr: 1.0e-7
ttpl_ratio: 2.0
dropout: 0.5
weight_decay: 0.01
warmup_epochs: 10
scheduler: True
lambda_con: 0.03
alpha_con: 5.0
temp_con: 0.07
temp_gd: 1.0
temp_decay: 0.999