# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "4,5,6,7"

# Paths
data_root: "/home/r20user17/Documents/ADHD200"
train_csv: "./datasets/splits/ADHD200_Training.csv"
test_csv: "./datasets/splits/ADHD200_Testing.csv"
checkpoints: "./checkpoints"

# Model Options
model: "graphseq"
embed_dim: 256
n_layers: 4
window_size: 9
cls_token: True
pooler: False

# Dataset Options
dataset: "ADHD200"
task: "DX"
atlas: "cc400"
cnp: "Age, Performance IQ"
cp: "Gender, Med Status"
n_views: 5

# Training Options
seed: 42
batch_size: 16
epochs: 400

# Optimization options
optimizer: "Adam"
lr: 1.0e-4
beta1: 0.9
beta2: 0.999
lr_ttt: 1.0e-4
dropout: 0.5
weight_decay: 0.03
warmup_epochs: 10
scheduler: False
lambda_cp: 0
lambda_cnp: 0
