# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "0,1,2,3"

# Paths
data_root: "/home/r20user17/Documents/ADHD200"
csv_path: "./datasets/splits"
checkpoints: "./checkpoints"
results: "./results"
reload: "./checkpoints/ADHD200_ho_DX_AUC_0.6784_.pth"

# Model Options
model: "graphseq"
embed_dim: 256
d_inner: 1024
n_layers: 1
n_heads: 8
d_x: 16
spatial_attention: True
temporal_attention: True
fusion: topl


# Dataset Options
dataset: "ADHD200"
task: "DX"
atlas: "cc400"
cnp: "Age, Performance IQ"
cp: "Gender"
n_views: 12


# Training Options
seed: 42
batch_size: 32
epochs: 60
mixup: True

# Optimization options
optimizer: "Adam"
pcgrad: False
lr: 2.0e-4
ttpl_lr: 1.0e-7
ttpl_ratio: 2.0
dropout: 0.5
weight_decay: 0.01
warmup_epochs: 10
scheduler: True
lambda_con: 0.03
alpha_con: 5.0
temp_con: 0.07
temp_gd: 1.0
temp_decay: 0.999
