# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "0,1,2,3"

# Paths
data_root: "/home/r20user17/Documents/ADHD200"
train_csv: "./datasets/splits/ADHD200_Training.csv"
test_csv: "./datasets/splits/ADHD200_Testing.csv"
checkpoints: "./checkpoints"

# Model Options
model: "graphseq"
embed_dim: 256
d_inner: 512
n_layers: 2
d_x: 16
brain_graph: ""


# Dataset Options
dataset: "ADHD200"
task: "DX"
atlas: "cc400"
cnp: "Age, Performance IQ"
cp: "Gender, Med Status"
n_views: 12

# Training Options
seed: 42
batch_size: 32
epochs: 100

# Optimization options
optimizer: "Adam"
pcgrad: False
lr: 2.0e-4
ttpl: 1.0e-7
dropout: 0.5
weight_decay: 0.1
warmup_epochs: 10
scheduler: True
lambda_con: 0.05
temp_con: 0.07
temp_gd: 1.0
temp_decay: 0.999
